name = "EltypeExtensions"
uuid = "583f92f5-06d6-4306-8236-316410defc98"
authors = ["Tianyi Pu <912396513@qq.com> and contributors"]
version = "0.0.2"

[weakdeps]
QuasiArrays = "c4ea9172-b204-11e9-377d-29865faadc5c"

[extensions]
EltypeExtensionsQuasiArraysExt = "QuasiArrays"

[compat]
Aqua = "0.8"
Documenter = "0.27, 1"
QuasiArrays = "0.11"
Test = "1"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
QuasiArrays = "c4ea9172-b204-11e9-377d-29865faadc5c"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Aqua", "Documenter", "Test"]
